version: "3.8"

services:
  tube-talk:
    build: .
    image: tube-talk
    container_name: tube-talk-app
    ports:
      - "${STREAMLIT_PORT}:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped